# Dev-only: author a feature-rich document with Word itself (realistic XML),
# then export Word's own PDF as the reference.
#   powershell -File tests/tools/word_features.ps1 tests/fixtures
param([string]$Dir = "tests/fixtures")
$ErrorActionPreference = 'Stop'
$Dir = (Resolve-Path $Dir).Path
$docx = [string](Join-Path $Dir "features.docx")
$pdf = [string](Join-Path (Join-Path $Dir "reference") "features.pdf")
$img = [string](Join-Path $Dir "sample.png")

python -c "from PIL import Image, ImageDraw; im=Image.new('RGB',(400,240),(70,130,180)); ImageDraw.Draw(im).ellipse((120,40,280,200),fill=(250,200,60)); im.save(r'$img')"

$w = New-Object -ComObject Word.Application
$w.Visible = $false
$w.DisplayAlerts = 0
$w.Options.BackgroundSave = $false
$d = $w.Documents.Add()
$d.SaveAs2($docx, 16)
$s = $w.Selection
$lorem = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat."

# title page with different first page header
$d.PageSetup.DifferentFirstPageHeaderFooter = -1
$s.Style = $d.Styles.Item(-63)  # wdStyleTitle
$s.TypeText("Feature Test Document")
$s.TypeParagraph()
$s.Style = $d.Styles.Item(-75)  # subtitle
$s.TypeText("Generated by Word for fidelity testing")
$s.TypeParagraph()
$s.Style = $d.Styles.Item(-1)
$s.TypeText("Table of contents:")
$s.TypeParagraph()
$tocRange = $s.Range
$s.TypeParagraph()
$s.InsertBreak(7)  # page break

# headings + footnotes
$s.Style = $d.Styles.Item(-2)
$s.TypeText("Introduction")
$s.TypeParagraph()
$s.Style = $d.Styles.Item(-1)
$s.TypeText("This paragraph has a footnote")
$d.Footnotes.Add($s.Range, [Type]::Missing, "This is the first footnote text, explaining something in detail.") | Out-Null
$s.TypeText(" and continues with more text. " + $lorem)
$d.Footnotes.Add($s.Range, [Type]::Missing, "Second footnote.") | Out-Null
$s.TypeParagraph()
$s.TypeText($lorem + " " + $lorem)
$s.TypeParagraph()

# multi-level list
$s.Style = $d.Styles.Item(-2)
$s.TypeText("Lists")
$s.TypeParagraph()
$s.Style = $d.Styles.Item(-1)
$tmpl = $w.ListGalleries.Item(3).ListTemplates.Item(1)  # outline numbered
$start = $s.Range.Start
$s.TypeText("First level item"); $s.TypeParagraph()
$s.TypeText("Another first level"); $s.TypeParagraph()
$s.TypeText("Nested item a"); $s.TypeParagraph()
$s.TypeText("Nested item b"); $s.TypeParagraph()
$s.TypeText("Back to first level"); $s.TypeParagraph()
$r = $d.Range($start, $s.Range.Start)
$r.ListFormat.ApplyListTemplate($tmpl, $false)
$r.Paragraphs.Item(3).Range.ListFormat.ListIndent()
$r.Paragraphs.Item(4).Range.ListFormat.ListIndent()
$s.Range.ListFormat.RemoveNumbers()
$s.Style = $d.Styles.Item(-1)

# bullets
$start = $s.Range.Start
$s.TypeText("Bullet one"); $s.TypeParagraph()
$s.TypeText("Bullet two with a longer text that will wrap onto the next line to check hanging indentation"); $s.TypeParagraph()
$r = $d.Range($start, $s.Range.Start)
$r.ListFormat.ApplyBulletDefault()
$s.Range.ListFormat.RemoveNumbers()

# table with repeated header and shading, long enough to cross a page
$s.Style = $d.Styles.Item(-2)
$s.TypeText("Big table")
$s.TypeParagraph()
$s.Style = $d.Styles.Item(-1)
$lines = @("Head 1`tHead 2`tHead 3`tHead 4")
for ($i = 2; $i -le 40; $i++) { $lines += "r$i c1`tr$i c2`tr$i c3`tr$i c4" }
$lines[4] = "r5 c1`tA cell with considerably more text so that it wraps within the cell and makes the row taller`tr5 c3`tr5 c4"
$tstart = $s.Range.Start
$s.TypeText(($lines -join "`r"))
$tr = $d.Range($tstart, $s.Range.End)
$t = $tr.ConvertToTable("`t", 40, 4)
$t.Style = $d.Styles.Item(-155)  # wdStyleTableLightGridAccent1
$t.Rows.Item(1).HeadingFormat = -1
$t.Rows.Item(1).Shading.BackgroundPatternColor = 12611584
$s.EndKey(6) | Out-Null
$s.TypeParagraph()

# floating picture with square wrapping + inline picture
$s.Style = $d.Styles.Item(-2)
$s.TypeText("Pictures")
$s.TypeParagraph()
$s.Style = $d.Styles.Item(-1)
$shape = $d.Shapes.AddPicture($img, $false, $true, 300, 20, 150, 90, $s.Range)
$shape.WrapFormat.Type = 4  # wdWrapTopBottom
$s.TypeText($lorem)
$s.TypeParagraph()
$s.InlineShapes.AddPicture($img) | Out-Null
$s.TypeParagraph()

# text box
$tb = $d.Shapes.AddTextbox(1, 72, 600, 200, 60, $s.Range)
$tb.TextFrame.TextRange.Text = "Text box content inside a shape"
$s.TypeText("Paragraph next to a text box. " + $lorem)
$s.TypeParagraph()

# two-column section
$s.InsertBreak(3)  # continuous section break
$d.Sections.Item($d.Sections.Count).PageSetup.TextColumns.SetCount(2)
for ($i = 1; $i -le 6; $i++) { $s.TypeText("Column text $i. " + $lorem); $s.TypeParagraph() }
$s.InsertBreak(3)
$d.Sections.Item($d.Sections.Count).PageSetup.TextColumns.SetCount(1)

# landscape section
$s.InsertBreak(2)  # next page section
$d.Sections.Item($d.Sections.Count).PageSetup.Orientation = 1
$s.Style = $d.Styles.Item(-2)
$s.TypeText("Landscape section")
$s.TypeParagraph()
$s.Style = $d.Styles.Item(-1)
$s.TypeText("Paragraph with borders and shading. " + $lorem)
$p = $s.Paragraphs.Item(1)
$p.Borders.Enable = -1
$p.Shading.BackgroundPatternColor = 14277081
$s.TypeParagraph()
$p = $s.Paragraphs.Item(1)
$p.Borders.Enable = 0
$p.Shading.BackgroundPatternColor = -16777216
$s.TypeText("Hyperlink: ")
$d.Hyperlinks.Add($s.Range, "https://example.com", [Type]::Missing, [Type]::Missing, "example.com") | Out-Null
$s.TypeParagraph()

# headers / footers
$sec = $d.Sections.Item(1)
$sec.Headers.Item(1).Range.Text = "Running header"
$sec.Headers.Item(2).Range.Text = "First page header"
$f = $sec.Footers.Item(1).Range
$f.Text = "Page "
$f.Collapse(0)
$f.Fields.Add($f, 33) | Out-Null  # wdFieldPage
$f.ParagraphFormat.Alignment = 1


$d.SaveAs2($docx, 16)
$d.ExportAsFixedFormat($pdf, 17)
$d.Close(0)
$w.Quit()
Write-Output "ok"





